use_frameworks!

platform :ios, '9.0'

target 'RxAlertController_Example' do
  pod 'RxAlertController', :path => '../'

  target 'RxAlertController_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.0'
  end
end
