use_frameworks!

platform :ios, '9.0'

target 'RxAlertController_Example' do
  pod 'RxAlertController', :path => '../'

  target 'RxAlertController_Tests' do
    inherit! :search_paths

    pod 'Quick'
    pod 'Nimble'
  end
end
